name: pybroker-experiments
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12
  - numpy<2 # https://github.com/TA-Lib/ta-lib-python/issues/378, https://github.com/TA-Lib/ta-lib-python/issues/661
  - pandas
  - pip
  - python-dotenv
  - scipy
  - ta-lib

  - pip:
      - lib-pybroker=0.21.2
      - numpy<2 # https://github.com/TA-Lib/ta-lib-python/issues/378, https://github.com/TA-Lib/ta-lib-python/issues/661

